---
abstract: 'Moose Like Types for Moo'
author:
  - 'Mateu X Hunter <hunter@missoula.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  IO::Handle: 0
  Moo: 0
  Test::Fatal: 0
  Test::More: 0
  perl: 5.006
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Types-MooseLike
requires:
  Data::Dumper::Concise: 0
  Exporter: 0
  List::Util: 0
  Scalar::Util: 0
  Sub::Quote: 0
  base: 0
  strict: 0
  strictures: 1
version: 0.02
